BUILD_HOME:=$(shell pwd)/../../..

include $(XDAQ_ROOT)/config/mfAutoconf.rules
include $(XDAQ_ROOT)/config/mfDefs.$(XDAQ_OS)

Project=daq
Package=bril/scripts
PackageName=brilscripts

PACKAGE_VER_MAJOR=1
PACKAGE_VER_MINOR=0
PACKAGE_VER_PATCH=0

Summary=run time scripts

Description=collection of run time scripts and setups

Authors=Zhen Xie

Link="https://twiki.cern.ch/twiki/bin/viewauth/CMS/LumiCalc"

include $(XDAQ_ROOT)/config/Makefile.rules
include $(XDAQ_ROOT)/config/mfSetupRPM.rules
