
all:
	$(MAKE) -C lumiHFLumiSaver
	$(MAKE) -C lumiHFHistoSaver
	$(MAKE) -C lumiHFLumiDipPublisher
	$(MAKE) -C lumiHFReadout

cleanall:
	-$(MAKE) -C lumiHFLumiSaver cleanall
	-$(MAKE) -C lumiHFHistoSaver cleanall
	-$(MAKE) -C lumiHFLumiDipPublisher cleanall
	-$(MAKE) -C lumiHFReadout cleanall
